"""add platforms table and game_platform join table

Revision ID: 3c7b23b5923b
Revises: c67434fb439c
Create Date: 2023-09-25 16:59:11.339145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7b23b5923b'
down_revision = 'c67434fb439c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_platform_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_game_platform_platform_id_platforms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platform')
    op.drop_table('platforms')
    # ### end Alembic commands ###
