"""update game price to float

Revision ID: 67933b5ca4e9
Revises: 4dbe7b30ad59
Create Date: 2023-09-27 21:22:51.597578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67933b5ca4e9'
down_revision = '4dbe7b30ad59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
