"""add carousel image to games table

Revision ID: c9e9cb7baa1a
Revises: 67933b5ca4e9
Create Date: 2023-10-04 09:52:17.171511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e9cb7baa1a'
down_revision = '67933b5ca4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carousel_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('carousel_image')

    # ### end Alembic commands ###
