"""add game trailer to games table

Revision ID: f26811762eb4
Revises: c9e9cb7baa1a
Create Date: 2023-10-04 21:31:21.051829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26811762eb4'
down_revision = 'c9e9cb7baa1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_trailer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('game_trailer')

    # ### end Alembic commands ###
